/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquina;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class PanelOperador extends javax.swing.JFrame {

    /**
     * Creates new form PanelOperador
     */
    
    
    public PanelOperador() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIngresar = new javax.swing.JTextField();
        txtRetirar = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtIStock = new javax.swing.JTextField();
        txtRStock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Panel de Operaciones");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Dulce o Salado?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ingresar Stock");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Retirar Stock");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Seleccione cantidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Seleccione cantidad");

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnRetirar.setText("RETIRAR");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtIStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIngresar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtRStock, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 191, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(200, 200, 200))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(228, 228, 228))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addGap(101, 101, 101))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIStock, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnRetirar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIStockActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(txtIStock.getText().trim().equalsIgnoreCase("Kitkat")){
             try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into kitkat (Kitkat) VALUES(?)");
                pst.setString(1, txtIngresar.getText().trim());

                pst.executeUpdate();
                txtIngresar.setText("");
                txtIStock.setText("");
                JOptionPane.showMessageDialog(null, "El ingreso de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
             
             
        } else if(txtIStock.getText().trim().equalsIgnoreCase("Bonobon")) {
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into bonobon (Bonobon) VALUES(?)");
                pst.setString(1, txtIngresar.getText().trim());

                pst.executeUpdate();
                txtIngresar.setText("");
                txtIStock.setText("");
                JOptionPane.showMessageDialog(null, "El ingreso de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        } else if(txtIStock.getText().trim().equalsIgnoreCase("Turron")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into turron (Turron) VALUES(?)");
                pst.setString(1, txtIngresar.getText().trim());

                pst.executeUpdate();
                txtIngresar.setText("");
                txtIStock.setText("");
                JOptionPane.showMessageDialog(null, "El ingreso de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        } else if(txtIStock.getText().trim().equalsIgnoreCase("Mani")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into mani (Mani) VALUES(?)");
                pst.setString(1, txtIngresar.getText().trim());

                pst.executeUpdate();
                txtIngresar.setText("");
                txtIStock.setText("");
                JOptionPane.showMessageDialog(null, "El ingreso de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        }
        else if(txtIStock.getText().trim().equalsIgnoreCase("Papas")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into papas (Papas) VALUES(?)");
                pst.setString(1, txtIngresar.getText().trim());

                pst.executeUpdate();
                txtIngresar.setText("");
                txtIStock.setText("");
                JOptionPane.showMessageDialog(null, "El ingreso de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        }
        
        else if(txtIStock.getText().trim().equalsIgnoreCase("Chocolate")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into chocolate (Chocolate) VALUES(?)");
                pst.setString(1, txtIngresar.getText().trim());

                pst.executeUpdate();
                txtIngresar.setText("");
                txtIStock.setText("");
                JOptionPane.showMessageDialog(null, "El ingreso de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        }
        
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        if(txtRStock.getText().trim().equalsIgnoreCase("Chocolate")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("delete from chocolate where Chocolate = ? limit 1");
                pst.setString(1, txtRetirar.getText().trim());

                pst.executeUpdate();
                txtRetirar.setText("");
                txtRStock.setText("");
                JOptionPane.showMessageDialog(null, "El retiro de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        } else if(txtRStock.getText().trim().equalsIgnoreCase("Turron")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("delete from turron where Turron = ? limit 1");
                pst.setString(1, txtRetirar.getText().trim());

                pst.executeUpdate();
                txtRetirar.setText("");
                txtRStock.setText("");
                JOptionPane.showMessageDialog(null, "El retiro de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        } else if(txtRStock.getText().trim().equalsIgnoreCase("Mani")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("delete from mani where Mani = ? limit 1");
                pst.setString(1, txtRetirar.getText().trim());

                pst.executeUpdate();
                txtRetirar.setText("");
                txtRStock.setText("");
                JOptionPane.showMessageDialog(null, "El retiro de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        } else if(txtRStock.getText().trim().equalsIgnoreCase("Papas")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("delete from papas where Papas = ? limit 1");
                pst.setString(1, txtRetirar.getText().trim());

                pst.executeUpdate();
                txtRetirar.setText("");
                txtRStock.setText("");
                JOptionPane.showMessageDialog(null, "El retiro de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        } else if(txtRStock.getText().trim().equalsIgnoreCase("Kitkat")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("delete from kitkat where Kitkat = ? limit 1");
                pst.setString(1, txtRetirar.getText().trim());

                pst.executeUpdate();
                txtRetirar.setText("");
                txtRStock.setText("");
                JOptionPane.showMessageDialog(null, "El retiro de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        } else if(txtRStock.getText().trim().equalsIgnoreCase("Bonobon")){
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/expendedora", "root", "");
                PreparedStatement pst = cn.prepareStatement("delete from bonobon where Bonobon = ? limit 1");
                pst.setString(1, txtRetirar.getText().trim());

                pst.executeUpdate();
                txtRetirar.setText("");
                txtRStock.setText("");
                JOptionPane.showMessageDialog(null, "El retiro de stock ha sido exitoso.");
            } catch (HeadlessException | SQLException e) {

            }
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       txtRStock.setText("");
       txtIStock.setText("");
       txtIngresar.setText("");
       txtRetirar.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelOperador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtIStock;
    private javax.swing.JTextField txtIngresar;
    private javax.swing.JTextField txtRStock;
    private javax.swing.JTextField txtRetirar;
    // End of variables declaration//GEN-END:variables
}
